defaults: &defaults
  base_url: "http://export.arxiv.org/api/query?"
  loaded_link: "http://arxiv.org/"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

